spring.application.name=reserva_cabanias

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/gup_reservas
spring.profiles.active=local
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA
# comprueba que tablas y clases java coinciden
spring.jpa.hibernate.ddl-auto=validate
#muestra SQL en consola
spring.jpa.show-sql=true
# fromatea SQL para que sea legible
spring.jpa.properties.hibernate.format_sql=true

# Puerto servidor
server.port=8080